### ISSUE TITLE
Where is database table

### ISSUE THREAD

**Issue by Evaexe117** [Spayker/a3wasp-server#2]
Hello !
First thanks for you'r job.
I have a question,
where i can find the table of the database ?

thanks

**Comment by Spayker** [comment]
Hey,

which one do you need?

**Comment by Evaexe117** [comment]
Hey !!

All the database table structure of a3wasp-server that work with extdb3.

Thanks !!

**Comment by Spayker** [comment]
It's not needed for normal game. Just remove ext3db mentions in scripts if they exist still there

**Comment by Evaexe117** [comment]
Thanks !
