### ISSUE TITLE
HQs not initialized at game start

### ISSUE THREAD

**Issue by Ezcoo** [Spayker/a3wasp-server#4]
Currently, HQs are not initialized properly when the game starts, which leads to HQ status being "Destroyed" upon match start and thus causing the mission to end almost instantly.

`fn_initServer.sqf`, line 241: 
```sqf
//--- start base
		missionNamespace setVariable ["WF_HEADLESSCLIENT_ID", 0];
		[_side, _pos] spawn {
		    Params ['_side', '_pos'];
		waitUntil{(missionNamespace getVariable "WF_HEADLESSCLIENT_ID") != 0};
		_hc = missionNamespace getVariable "WF_HEADLESSCLIENT_ID";
		if(_hc > 0) then {
            [_side, _pos, missionNamespace getVariable format ["WF_NEURODEF_%1_BASE", _side]] remoteExecCall ["WFHC_FNC_CreateStartupBase", _hc]
            }
        };
```

Note that e.g. `WF_NEURODEF_EAST_BASE` is defined on server only. The base templates are defined in server mod in file `Init_Defenses.sqf`:

```sqf
missionNamespace setVariable ['WF_NEURODEF_WEST_BASE',[
	["USMC_WarfareBLightFactory",[9.57227,12.7861,-0.600006],90],
    ["USMC_WarfareBUAVterminal",[-8.06445,15.25,0],0],
    ["USMC_WarfareBBarracks",[8.91406,-14.2578,-0.600006],0],
    ["LAV25_HQ_unfolded",[-34.4092,-30.9697,0],90],
    ["Base_WarfareBBarrier10xTall",[20.6318,6.98145,0],90],
    ["Base_WarfareBBarrier10xTall",[-23.4258,-7.65527,0],90],
    ["Base_WarfareBBarrier10xTall",[-0.323242,-30.1289,0],0],
    ["Base_WarfareBBarrier10xTall",[-0.0878906,29.1484,0],0],
    ["Land_HBarrierTower_F",[17.2803,24.665,0],180],
    ["Land_HBarrierTower_F",[16.2432,-25.417,0],90],
    ["Base_WarfareBBarrier10xTall",[20.6768,-22.3057,0],90],
    ["Base_WarfareBBarrier10xTall",[20.6768,22.2783,0],90],
    ["Land_HBarrierTower_F",[-19.0898,-24.624,0],0],
    ["Land_HBarrierTower_F",[-17.3887,26.0361,0],270],
    ["Base_WarfareBBarrier10xTall",[-23.4258,22.4785,0],90],
    ["Base_WarfareBBarrier10xTall",[-23.4258,-22.6533,0],90],
    ["Base_WarfareBBarrier10xTall",[14.6885,-30.0479,0],0],
    ["Base_WarfareBBarrier10xTall",[14.6885,29.0986,0],0],
    ["Base_WarfareBBarrier10xTall",[-15.6221,-30.1768,0],0],
    ["Base_WarfareBBarrier10xTall",[-15.415,29.1445,0],0],
    ["Land_JumpTarget_F",[-34.8984,7.93555,0],0],
    ["Land_JumpTarget_F",[-34.8984,-9.33203,0],0],
    ["Land_JumpTarget_F",[-34.8984,25.0459,0],0],
        ["Land_HelipadCircle_F",[30.91406, -60,-0.600006],0],
        ["Land_HelipadCircle_F",[60.91406, -90,-0.600006],90]
    ]]
```

**Comment by Ezcoo** [comment]
To further clarify just to make sure: the startup base creation is delegated to HC, but the base template configs are defined on server only.

**Comment by Spayker** [comment]
Init server script contains following instruction:

`_hc = missionNamespace getVariable "WF_HEADLESSCLIENT_ID";
		if(_hc > 0) then {
            [_side, _pos, missionNamespace getVariable format ["WF_NEURODEF_%1_BASE", _side]] remoteExecCall ["WFHC_FNC_CreateStartupBase", _hc]
            }
        };`

It gets array of base template objects and sends it to HC side which will proceed with base deployment finally.
The process should be done this way. Reason: server side should create less objects by itself that increases long term performance of game sessions.

**Comment by Ezcoo** [comment]
Ah, I see. Something is breaking the HQ init process, though, as HQ doesn't spawn at the beginning of the match, and thus leads to instant end of the match.

**Comment by Spayker** [comment]
investigate and provide logs

**Comment by Ezcoo** [comment]
I checked the logfiles and one of the few scripting errors this seems the most likely candidate:

```
15:36:38 Error in expression <
};


if (isHeadLessClient) then { call WFHC_fnc_initHc };>
15:36:38   Error position: <WFHC_fnc_initHc };>
15:36:38   Error Undefined variable in expression: wfhc_fnc_inithc
15:36:38 File mpmissions\__CUR_MP.altis\init.sqf..., line 140
```

**Comment by Spayker** [comment]
check if HC bat file contains HCmod included in -mod

**Comment by Ezcoo** [comment]
You're correct. My mod list in HC batch file was incorrect because the mod names have changed. I fixed the server batch file thought I had fixed the HC file too, but I hadn't. It works now. Thanks again! 👍
